# Generated by Django 4.0.4 on 2022-05-31 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_user_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='account_no', primary_key=True, serialize=False, verbose_name='account no'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_account', models.IntegerField(verbose_name='transfer account')),
                ('transfer_amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='transfer amount')),
                ('notes', models.CharField(max_length=200, verbose_name='notes')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='transfer date')),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
