# Generated by Django 4.0.4 on 2022-05-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_customers_password_customers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
