# Generated by Django 4.0.4 on 2022-06-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=False, verbose_name='first login'),
        ),
    ]
